### ISSUE TITLE
Baselines

### ISSUE THREAD

**Issue by Old-Shatterhand** [ilsenatorov/rindti#44]
prediction baseline based on
- [x] majority prediction based on trainset (regardless of drug and target)
- [x] majority prediction of target behavior based on trainset
- [x] majority prediction of drug behavior based on trainset
- [x] majority prediction of drug and target based on trainset
- [x] probabilistic prediction of target based on trainset
- [x] probabilistic prediction of drug behavior based on trainset
- [x] probabilistic prediction of drug and target based on trainset

**Comment by ilsenatorov** [comment]
I think it makes sense to use the output of parse_dataset ( or split_dataset) as the input to the baselines because it is completely devoid of any structural information?

I think it would be useful to have a snakemake rule that creates a plotly graph/dash vis that just shows all the necessary information about the dataset ( including baseline accuracies.

**Comment by Old-Shatterhand** [comment]
I'd go for split_dataset as this contains the same splits as the training and we fit all models on the same splits. This makes the results comparable (IMO)

**Comment by Old-Shatterhand** [comment]
I'm not quite sure, if they're correct, the metrics on my 96% unbalanced dataset are more or less the same as without sampling...
